name: 'Docker Build and Push'

description: 'Builds and pushes a Docker image to Docker Hub'

inputs:
  docker-hub-account:
    description: 'Docker Hub username'
    required: true
  image-name:
    description: 'Docker image name'
    required: true
  image-version:
    description: 'Docker image version/tag'
    required: false
    default: 'latest'
  project-path:
    description: 'Path to the Dockerfile'
    required: true
  docker-username:
    description: 'Docker Hub login username'
    required: true
  docker-password:
    description: 'Docker Hub login password'
    required: true

runs:
  using: "composite"
  steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@e468171a9de216ec08956ac3ada2f0791b6bd435 # releases v3.11.1

    - name: Log in to Docker Hub
      uses: docker/login-action@5e57cd118135c172c3672efd75eb46360885c0ef # releases v3.6.0
      with:
        username: ${{ inputs.docker-username }}
        password: ${{ inputs.docker-password }}

    - name: Build Docker image
      run: |
        docker build -t ${{ inputs.docker-hub-account }}/${{ inputs.image-name }}:${{ inputs.image-version }} ${{ inputs.project-path }}
      shell: bash

    - name: Push Docker image
      run: |
        docker push ${{ inputs.docker-hub-account }}/${{ inputs.image-name }}:${{ inputs.image-version }}
      shell: bash
