name: 'Trivy Vulnerability Scan and Save Results'

description: 'Scans a Docker image for vulnerabilities using Trivy and saves the results as an artifact'

inputs:
  docker-hub-account:
    description: 'Docker Hub username'
    required: true
  image-name:
    description: 'Docker image name'
    required: true
  image-version:
    description: 'Docker image version/tag to scan'
    required: false
    default: 'latest'

runs:
  using: "composite"
  steps:
    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@b6643a29fecd7f34b3597bc6acb0a98b03d33ff8 # releases v0.33.1
      continue-on-error: true
      with:
        image-ref: "${{ inputs.docker-hub-account }}/${{ inputs.image-name }}:${{ inputs.image-version }}"
        exit-code: 1
        ignore-unfixed: true
        format: "table"
        severity: "CRITICAL,HIGH,MEDIUM,LOW"
        output: "aquasecurity-scan.txt"

    - name: Temporarily save Trivy results
      uses: actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4 # releases v5.0.0
      with:
        name: "aquasecurity-scan"
        path: "./aquasecurity-scan.txt"
        retention-days: 1
