name: Install Tools on Ubuntu

on:
  workflow_dispatch:
    inputs:
      mssql-password:
        description: 'Password for MSSQL'
        required: true
        type: string
        default: '12345'

jobs:
  install-tools:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Update Packages
        continue-on-error: true
        run: |
          echo "UPDATE"
          sudo apt-get update
          echo

      - name: Upgrade Packages
        continue-on-error: true
        run: |
          echo "UPGRADE"
          sudo apt-get upgrade -y
          echo

      - name: Install wget
        continue-on-error: true
        run: |
          echo "INSTALL WGET"
          sudo apt-get install wget -y
          wget --version
          echo

      - name: Install curl
        continue-on-error: true
        run: |
          echo "INSTALLATION 'curl'"
          sudo apt-get install curl -y
          curl --version
          echo

      - name: Install unzip
        continue-on-error: true
        run: |
          echo "INSTALLATION 'unzip'"
          sudo apt-get install unzip -y
          if unzip --version; then
            echo "'unzip' installed successfully"
          else
            echo "the newest version of 'unzip' already installed"
          fi
          echo

      - name: Install netstat
        continue-on-error: true
        run: |
          echo "INSTALLATION 'netstat'"
          sudo apt-get install net-tools -y
          netstat --version
          echo

      - name: Install xvfb
        continue-on-error: true
        run: |
          echo "INSTALLATION 'xvfb'"
          sudo apt-get install xvfb -y
          # Xvfb --version
          xvfb --version
          echo

      - name: Install .NET 8.0 SDK
        continue-on-error: true
        run: |
          echo "INSTALLATION '.NET 8.0 SDK'"
          sudo apt-get install -y wget apt-transport-https
          wget https://packages.microsoft.com/config/ubuntu/22.04/packages-microsoft-prod.deb
          sudo dpkg -i packages-microsoft-prod.deb
          sudo apt-get install -y dotnet-sdk-8.0
          dotnet --version
          rm *.deb
          echo "Installation completed and temporary files deleted."
          echo

      - name: Download Google Chrome
        continue-on-error: true
        run: |
          echo "DOWNLOAD 'Google Chrome'"
          wget -N https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb -O /tmp/google-chrome-stable_current_amd64.deb
          echo

      - name: Install Google Chrome
        continue-on-error: true
        run: |
          echo "INSTALLATION 'Google Chrome'"
          sudo apt-get install -y /tmp/google-chrome-stable_current_amd64.deb
          google-chrome --version
          echo

      - name: Install Docker
        continue-on-error: true
        run: |
          echo "INSTALLATION 'Docker'"
          sudo apt-get install -y apt-transport-https ca-certificates curl software-properties-common
          curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
          sudo add-apt-repository -y "deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable"
          apt-cache policy docker-ce
          sudo apt-get install -y docker-ce
          sudo systemctl status docker
          # sudo usermod -aG docker ${USER}
          sudo usermod -aG docker $(whoami)
          echo

      - name: Pull MSSQL image and start the container
        env:
          SA_PASSWORD: ${{ inputs.mssql-password }}
        run: |
          echo "Pull MSSQL image and start the container"
          docker pull mcr.microsoft.com/mssql/server:2022-latest
          docker run -e "ACCEPT_EULA=Y" -e "MSSQL_SA_PASSWORD=${{ env.SA_PASSWORD }}" -p 1433:1433 --name sql1 --hostname sql1 -d mcr.microsoft.com/mssql/server:2022-latest
          docker update --restart=always sql1
          echo
